export const ActionsTypes = {

    OPEN_FORM: 'modal:OPEN_FORM',
    OPEN_FORM_EDIT: 'modal:OPEN_FORM_EDIT',
    CLOSE_FORM_EDIT: 'modal:CLOSE_FORM_EDIT',
    CLOSE_FORM: 'modal:CLOSE_FORM',

    USER_GET_ALL_REQUEST: 'user:GET_ALL_REQUEST',
    USER_GET_ALL_SUCCESS: 'user:GET_ALL_SUCCESS',
    USER_GET_ALL_FAILURE: 'user:GET_ALL_FAILURE',
    USER_GET_REQUEST: 'user:GET_REQUEST_REQUEST',
    USER_GET : 'user: USER_GET_SUCCESS',
    USER_UPDATE_REQUEST: 'user:USER_UPDATE_REQUEST',
    USER_UPDATE : 'user:USER_UPDATE_SUCCESS',
    USER_CREATE_REQUEST: 'user:CREATE_REQUEST',
    USER_REMOVE_REQUEST: 'user:REMOVE_REQUEST',
}