export const ActionsTypes = {
    OPEN_FORM: 'user:OPEN_FORM',
    CLOSE_FORM: 'user:CLOSE_FORM',
    USER_GET_ALL_REQUEST: 'user:GET_ALL_REQUEST',
    USER_GET_ALL_SUCCESS: 'user:GET_ALL_SUCCESS',
    USER_GET_ALL_FAILURE: 'user:GET_ALL_FAILURE',
    USER_GET_REQUEST: 'user:GET_REQUEST_REQUEST',
    USER_CREATE_REQUEST: 'user:CREATE_REQUEST',
    USER_UPDATE_REQUEST: 'user:UPDATE_REQUEST',
    USER_REMOVE_REQUEST: 'user:REMOVE_REQUEST',
}